### ISSUE TITLE
'right click' menu appearing when opening spotlight

### ISSUE THREAD

**Issue by cgoliver** [spotlightify/spotlightify#54]
Thanks for the great repo!

Just one small strange thing.. whenever I open the spotlight with ctrl+enter, a right click menu appears behind the spotlight and kills the spotlight unless I start typing right away.

I'm on Mac OS 10.15.5. Wondering if there is some kind of mapping collision, or if its related to the app.

I'm attaching a screenshot.

Thanks!

![Screen Shot 2020-07-10 at 10 36 35 AM](https://user-images.githubusercontent.com/2636451/87166218-3d276c00-c299-11ea-9915-41799eee3486.png)

Not sure if this is related, but I get the following error on startup each time:

```
[CACHE] [ARTIST] Skipping caching, last updated Fri 10 Jul 10:13:43 2020
HTTP Error for GET to https://api.spotify.com/v1/albums/7JbUvdIr1yepIxZy9rt3un/tracks/ returned 404 due to error
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/Users/carlosgonzalezoliver/Projects/spotlightify/venv/lib/python3.7/site-packages/spotipy/client.py", line 175, in _internal_call
    response.raise_for_status()
  File "/Users/carlosgonzalezoliver/Projects/spotlightify/venv/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.spotify.com/v1/albums/7JbUvdIr1yepIxZy9rt3un/tracks/?limit=50&offset=0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/carlosgonzalezoliver/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/carlosgonzalezoliver/Projects/spotlightify/caching/threads.py", line 278, in run
    song_data = self.get_all(self.sp.album_tracks(album_id=album["id"]))
  File "/Users/carlosgonzalezoliver/Projects/spotlightify/venv/lib/python3.7/site-packages/spotipy/client.py", line 358, in album_tracks
    "albums/" + trid + "/tracks/", limit=limit, offset=offset, market=market
  File "/Users/carlosgonzalezoliver/Projects/spotlightify/venv/lib/python3.7/site-packages/spotipy/client.py", line 210, in _get
    return self._internal_call("GET", url, payload, kwargs)
  File "/Users/carlosgonzalezoliver/Projects/spotlightify/venv/lib/python3.7/site-packages/spotipy/client.py", line 190, in _internal_call
    headers=response.headers,
spotipy.exceptions.SpotifyException: http status: 404, code:-1 - https://api.spotify.com/v1/albums/7JbUvdIr1yepIxZy9rt3un/tracks/?limit=50&offset=0:
 error

```

**Comment by MarkMcMoran** [comment]
Hi, 

Are you using the most recent commit of the master? If not, please pull the most recent version.

**Comment by cgoliver** [comment]
Hi! Thanks for the reply! Yeah I just pulled and relaunched `app.py` and I get the same behaviour. Although the exception pasted above is no longer happening.

**Comment by petergmurphy** [comment]
We will be working on implementing a fix in the next few days. Thanks for bringing this to our attention.

**Comment by petergmurphy** [comment]
Hey there,

I'm closing this issue because Spotlightify has been completely rewritten with a new Golang backend and React Typescript frontend. The latest version is much improved—give it a try and let me know what you think!

Cheers,
Peter
